/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint.view;

import java.awt.Color;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;
import paint.controller.DrawingEngineImplementation;

/**
 *
 * @author Alex Laptop
 */
public class paintapp extends javax.swing.JFrame {

    /**
     * Creates new form paintapp
     */
    public paintapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        my1 = new paint.view.My();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        myCanvas2 = new paint.view.MyCanvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint Application");
        setResizable(false);

        jToolBar1.setRollover(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Color_Wheel_48px.png"))); // NOI18N
        jLabel2.setText("Color");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Undo_48px_5.png"))); // NOI18N
        jLabel3.setText("Undo");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel3);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Redo_48px.png"))); // NOI18N
        jLabel4.setText("Redo");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Save_48px.png"))); // NOI18N
        jLabel5.setText("Save");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel5);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Open_48px.png"))); // NOI18N
        jLabel8.setText("Open");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel8);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Move_48px.png"))); // NOI18N
        jLabel6.setText("Move");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel6);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Trash_48px.png"))); // NOI18N
        jLabel1.setText("Delete");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jToolBar1.add(jLabel1);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Resize_48px.png"))); // NOI18N
        jLabel7.setText("Resize");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel7);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Copy_48px.png"))); // NOI18N
        jLabel16.setText("Copy");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel16);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Clear_Symbol_48px.png"))); // NOI18N
        jLabel17.setText("Clear");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel17);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Cursor_48px.png"))); // NOI18N
        jLabel14.setText("Cursor ");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });
        jToolBar1.add(jLabel14);

        jTabbedPane3.addTab("Tools", jToolBar1);

        jToolBar2.setRollover(true);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Circle_48px_1.png"))); // NOI18N
        jLabel9.setText("Circle");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Line_48px.png"))); // NOI18N
        jLabel10.setText("Line Segment");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Oval_48px.png"))); // NOI18N
        jLabel11.setText("Ellipse");
        jLabel11.setToolTipText("");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel11);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Rectangular_48px_2.png"))); // NOI18N
        jLabel12.setText("Rectangle");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel12);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Triangle_48px.png"))); // NOI18N
        jLabel13.setText("Triangle");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel13);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paintproject/icons/icons8_Square_48px_1.png"))); // NOI18N
        jLabel15.setText("Square");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jToolBar2.add(jLabel15);

        jCheckBox1.setText("Filled");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar2.add(jCheckBox1);

        jTabbedPane3.addTab("Shape", jToolBar2);

        myCanvas2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout myCanvas2Layout = new javax.swing.GroupLayout(myCanvas2);
        myCanvas2.setLayout(myCanvas2Layout);
        myCanvas2Layout.setHorizontalGroup(
            myCanvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 686, Short.MAX_VALUE)
        );
        myCanvas2Layout.setVerticalGroup(
            myCanvas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myCanvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myCanvas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
   myCanvas2.setCurrentMode(2);
    }//GEN-LAST:event_jLabel14MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        myCanvas2.setCurrentShapeType(4);
           myCanvas2.setCurrentMode(1);
                   myCanvas2.setCurrentShapeObjectNull();
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        myCanvas2.setCurrentShapeType(3);
           myCanvas2.setCurrentMode(1);
             myCanvas2.setCurrentShapeObjectNull();
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked

    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        myCanvas2.setCurrentShapeType(5);
             myCanvas2.setCurrentMode(1);
               myCanvas2.setCurrentShapeObjectNull();
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        myCanvas2.setCurrentShapeType(2);
             myCanvas2.setCurrentMode(1);
               myCanvas2.setCurrentShapeObjectNull();
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        myCanvas2.setCurrentShapeType(1);
             myCanvas2.setCurrentMode(1);
               myCanvas2.setCurrentShapeObjectNull();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
ColorPalatte c= new ColorPalatte();
c.dialog.setVisible(true);
myCanvas2.setCurrentShapeColor(c.colorChooser.getColor());
if(myCanvas2.isIsSelected())
myCanvas2.setCurrentShapeColor(c.colorChooser.getColor());

  
    }//GEN-LAST:event_jLabel2MousePressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected() ){
           myCanvas2.setCurrentShapeFilled(true);
       }
       else {
       myCanvas2.setCurrentShapeFilled(false);
       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
myCanvas2.setCurrentMode(3);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if (myCanvas2.getCurrentShapeObject() != null) {
            DrawingEngineImplementation.getinstance().removeShape(myCanvas2.getCurrentShapeObject());
        }
        //DrawingEngineImplementation.getinstance().redo();
        myCanvas2.setCurrentShapeObjectNull();
        myCanvas2.repaint();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        myCanvas2.setCurrentShapeType(6);
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
    if (myCanvas2.getCurrentShapeObject()!=null)
        {
            try {
                myCanvas2.creatingClone();
            } catch (CloneNotSupportedException ex) {
                Logger.getLogger(paintapp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        myCanvas2.repaint();
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed

            myCanvas2.setCurrentShapeObjectNull();
        DrawingEngineImplementation.getinstance().undo();
        myCanvas2.setCurrentShapeObjectNull();
        myCanvas2.setCurrentMode(2);
        myCanvas2.repaint();
    
    }//GEN-LAST:event_jLabel3MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
myCanvas2.setCurrentMode(6);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
DrawingEngineImplementation.getinstance().removeall();
myCanvas2.repaint();
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
 String[] options = {"XML", "JSON"}; 
 int x = JOptionPane.showOptionDialog(null, "XML OR JSON?",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
if(x == 0 ){
     JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Specify a file to save"); 
 FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter(
     "xml files (*.xml)", "xml");
	fileChooser.setFileFilter(xmlfilter);
int userSelection = fileChooser.showSaveDialog(null);
 
if (userSelection == JFileChooser.APPROVE_OPTION) {
   DrawingEngineImplementation.getinstance().save(fileChooser.getSelectedFile().getAbsolutePath());
  // System.out.println("Save as file: " + fileToSave.getAbsolutePath());
  	
			}


  
			
}else{
     JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Specify a file to save");   
 
int userSelection = fileChooser.showSaveDialog(null);
 
if (userSelection == JFileChooser.APPROVE_OPTION) {
    
      DrawingEngineImplementation.getinstance().save(fileChooser.getSelectedFile().getAbsolutePath());
      
    //System.out.println("Save as file: " + fileToSave.getAbsolutePath());
}

    
}

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
String[] options = {"XML", "JSON"}; 
 int x = JOptionPane.showOptionDialog(null, "XML OR JSON?",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
if(x == 0 ){
 JFileChooser fileChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
 FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter(
     "xml files (*.xml)", "xml");
		int returnValue = fileChooser.showOpenDialog(null);
		// int returnValue = jfc.showSaveDialog(null);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
               			DrawingEngineImplementation.getinstance().load(fileChooser.getSelectedFile().getAbsolutePath());
			
		}        // TODO add your handling code here:

				myCanvas2.repaint();
			
}else{
   
     JFileChooser fileChooser= new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

		int returnValue=fileChooser.showOpenDialog(null);
		// int returnValue = jfc.showSaveDialog(null);

		if (returnValue == JFileChooser.APPROVE_OPTION) {
                   
			DrawingEngineImplementation.getinstance().load(fileChooser.getSelectedFile().getAbsolutePath());
		}        // TODO add your handling code here:
                                        
    
				myCanvas2.repaint();
}
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
    myCanvas2.setCurrentShapeObjectNull();
        DrawingEngineImplementation.getinstance().redo();
        myCanvas2.setCurrentShapeObjectNull();
        myCanvas2.setCurrentMode(2);
        myCanvas2.repaint();
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
 if (myCanvas2.getCurrentShapeObject() != null) {
            DrawingEngineImplementation.getinstance().removeShape(myCanvas2.getCurrentShapeObject());
        }
        //DrawingEngineImplementation.getinstance().redo();
        myCanvas2.setCurrentShapeObjectNull();
        myCanvas2.repaint();

    }//GEN-LAST:event_jLabel1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paintapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paintapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paintapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paintapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paintapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private paint.view.My my1;
    private paint.view.MyCanvas myCanvas2;
    // End of variables declaration//GEN-END:variables
}
